/**
 * AI Trader reflection service — manages post-trade reflections generated by AI.
 *
 * When an EdgeFinder trade closes, a Haiku call produces a structured reflection
 * capturing what the thesis was, what happened, and actionable lessons. Future
 * Judge (Tier 3) prompts retrieve relevant past reflections as "experience memory".
 *
 * @module ai-trader-reflection-service
 */
import { db } from "./client"
import { safeIso } from "./utils"
import type {
  AiTraderReflectionData,
  AiTraderProfile,
  AiTraderTechnique,
  AiTraderMarketRegime,
  AiTraderSession,
  TradeDirection,
  TradingMode,
} from "@fxflow/types"

/** Trade outcome for reflections — cancelled trades are excluded. */
type ReflectionOutcome = "win" | "loss" | "breakeven"

// ─── Mappers ────────────────────────────────────────────────────────────────

function toReflectionData(row: {
  id: string
  opportunityId: string
  instrument: string
  direction: string
  profile: string
  confidence: number
  outcome: string
  realizedPL: number
  entryRationale: string | null
  reflection: string
  lessonsLearned: string
  primaryTechnique: string | null
  regime: string | null
  session: string | null
  model: string | null
  inputTokens: number
  outputTokens: number
  cost: number
  closedAt: Date
  createdAt: Date
}): AiTraderReflectionData {
  return {
    id: row.id,
    opportunityId: row.opportunityId,
    instrument: row.instrument,
    direction: row.direction as TradeDirection,
    profile: row.profile as AiTraderProfile,
    confidence: row.confidence,
    outcome: row.outcome as "win" | "loss" | "breakeven",
    realizedPL: row.realizedPL,
    entryRationale: row.entryRationale,
    reflection: row.reflection,
    lessonsLearned: row.lessonsLearned,
    primaryTechnique: row.primaryTechnique as AiTraderTechnique | null,
    regime: row.regime as AiTraderMarketRegime | null,
    session: row.session as AiTraderSession | null,
    model: row.model,
    inputTokens: row.inputTokens,
    outputTokens: row.outputTokens,
    cost: row.cost,
    closedAt: safeIso(row.closedAt),
    createdAt: safeIso(row.createdAt),
  }
}

// ─── Types ──────────────────────────────────────────────────────────────────

export interface CreateReflectionInput {
  /** OANDA account the closed trade was placed on. */
  account: TradingMode
  opportunityId: string
  instrument: string
  direction: TradeDirection
  profile: AiTraderProfile
  confidence: number
  outcome: ReflectionOutcome
  realizedPL: number
  entryRationale: string | null
  reflection: string
  lessonsLearned: string
  primaryTechnique?: AiTraderTechnique | null
  regime?: AiTraderMarketRegime | null
  session?: AiTraderSession | null
  model?: string
  inputTokens?: number
  outputTokens?: number
  cost?: number
  closedAt: Date
}

// ─── Mutations ──────────────────────────────────────────────────────────────

/** Create a new post-trade reflection record. */
export async function createReflection(
  input: CreateReflectionInput,
): Promise<AiTraderReflectionData> {
  const row = await db.aiTraderReflection.create({
    data: {
      account: input.account,
      opportunityId: input.opportunityId,
      instrument: input.instrument,
      direction: input.direction,
      profile: input.profile,
      confidence: input.confidence,
      outcome: input.outcome,
      realizedPL: input.realizedPL,
      entryRationale: input.entryRationale,
      reflection: input.reflection,
      lessonsLearned: input.lessonsLearned,
      primaryTechnique: input.primaryTechnique ?? null,
      regime: input.regime ?? null,
      session: input.session ?? null,
      model: input.model ?? null,
      inputTokens: input.inputTokens ?? 0,
      outputTokens: input.outputTokens ?? 0,
      cost: input.cost ?? 0,
      closedAt: input.closedAt,
    },
  })
  return toReflectionData(row)
}

// ─── Queries ────────────────────────────────────────────────────────────────

/**
 * Retrieve relevant past reflections for a given pair + profile.
 * Returns up to `limit` reflections, prioritising same instrument, then same profile.
 * Recency-weighted (ORDER BY createdAt DESC).
 */
export async function getRelevantReflections(
  instrument: string,
  profile: AiTraderProfile,
  limit = 3,
  account?: TradingMode,
): Promise<AiTraderReflectionData[]> {
  // First: same instrument + same profile (optionally same account — lessons
  // from practice inform live and vice versa, so account scoping is opt-in
  // rather than default).
  const exactWhere: Record<string, unknown> = { instrument, profile }
  if (account) exactWhere.account = account
  const exact = await db.aiTraderReflection.findMany({
    where: exactWhere,
    orderBy: { createdAt: "desc" },
    take: limit,
  })

  const results = exact.map(toReflectionData)

  // If we have enough, return
  if (results.length >= limit) return results.slice(0, limit)

  // Fill remaining slots from same profile, different instrument
  const remaining = limit - results.length
  const existingIds = results.map((r) => r.id)
  const broaderWhere: Record<string, unknown> = {
    profile,
    instrument: { not: instrument },
    id: { notIn: existingIds },
  }
  if (account) broaderWhere.account = account
  const broader = await db.aiTraderReflection.findMany({
    where: broaderWhere,
    orderBy: { createdAt: "desc" },
    take: remaining,
  })

  return [...results, ...broader.map(toReflectionData)]
}

/** Get a single reflection by opportunity ID. */
export async function getReflectionByOpportunityId(
  opportunityId: string,
): Promise<AiTraderReflectionData | null> {
  const row = await db.aiTraderReflection.findUnique({
    where: { opportunityId },
  })
  return row ? toReflectionData(row) : null
}

/** Check if a reflection already exists for an opportunity. */
export async function hasReflection(opportunityId: string): Promise<boolean> {
  const count = await db.aiTraderReflection.count({
    where: { opportunityId },
  })
  return count > 0
}

// ─── Cleanup ────────────────────────────────────────────────────────────────

/** Delete reflections older than the given number of days. */
export async function cleanupOldReflections(days = 180): Promise<number> {
  const cutoff = new Date()
  cutoff.setDate(cutoff.getDate() - days)

  const result = await db.aiTraderReflection.deleteMany({
    where: { createdAt: { lt: cutoff } },
  })
  return result.count
}
