#!/bin/bash
set -euo pipefail

# ─── FXFlow Cloudflare Tunnel Setup ──────────────────────────────────────────
#
# This script sets up a Cloudflare Tunnel for remote access to FXFlow.
# It will:
#   1. Install cloudflared (if not installed)
#   2. Authenticate with Cloudflare
#   3. Create a tunnel
#   4. Generate the config file
#   5. Optionally set up auto-start on macOS
#
# Prerequisites:
#   - A Cloudflare account (free tier is fine)
#   - Homebrew installed (for macOS)
#
# Usage: ./scripts/setup-tunnel.sh

TUNNEL_NAME="${TUNNEL_NAME:-fxflow}"
LOCAL_PORT="${LOCAL_PORT:-3000}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  FXFlow — Cloudflare Tunnel Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Step 1: Install cloudflared
if ! command -v cloudflared &>/dev/null; then
  echo "→ Installing cloudflared via Homebrew..."
  brew install cloudflare/cloudflare/cloudflared
else
  echo "✓ cloudflared is installed ($(cloudflared --version 2>&1 | head -1))"
fi
echo ""

# Step 2: Login to Cloudflare
echo "→ Authenticating with Cloudflare..."
echo "  This will open your browser. Log in and authorize cloudflared."
echo ""
cloudflared tunnel login
echo ""
echo "✓ Authenticated with Cloudflare"
echo ""

# Step 3: Create tunnel
echo "→ Creating tunnel '${TUNNEL_NAME}'..."
TUNNEL_OUTPUT=$(cloudflared tunnel create "${TUNNEL_NAME}" 2>&1)
echo "${TUNNEL_OUTPUT}"

# Extract tunnel ID from output
TUNNEL_ID=$(echo "${TUNNEL_OUTPUT}" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)

if [ -z "${TUNNEL_ID}" ]; then
  echo ""
  echo "⚠  Could not extract tunnel ID. If the tunnel already exists, find it with:"
  echo "   cloudflared tunnel list"
  echo ""
  read -rp "Enter your tunnel ID: " TUNNEL_ID
fi

echo ""
echo "✓ Tunnel created: ${TUNNEL_ID}"
echo ""

# Step 4: Generate config
CONFIG_DIR="${HOME}/.cloudflared"
CONFIG_FILE="${CONFIG_DIR}/config.yml"

echo "→ Writing config to ${CONFIG_FILE}..."

cat > "${CONFIG_FILE}" << EOF
# FXFlow Cloudflare Tunnel Config
# Generated by setup-tunnel.sh on $(date +%Y-%m-%d)

tunnel: ${TUNNEL_ID}
credentials-file: ${CONFIG_DIR}/${TUNNEL_ID}.json

ingress:
  - service: http://localhost:${LOCAL_PORT}
EOF

echo "✓ Config written"
echo ""

# Step 5: Show the tunnel URL
echo "→ Your tunnel will be available at:"
echo ""
echo "   https://${TUNNEL_ID}.cfargotunnel.com"
echo ""
echo "   You can also route it to a custom domain with:"
echo "   cloudflared tunnel route dns ${TUNNEL_NAME} fxflow.yourdomain.com"
echo ""

# Step 6: Auto-start (macOS launchd)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Auto-Start Setup (macOS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -rp "Set up auto-start on login? (y/n): " AUTOSTART

if [ "${AUTOSTART}" = "y" ] || [ "${AUTOSTART}" = "Y" ]; then
  PLIST_DIR="${HOME}/Library/LaunchAgents"
  PLIST_FILE="${PLIST_DIR}/com.fxflow.tunnel.plist"
  CLOUDFLARED_PATH=$(which cloudflared)
  LOG_FILE="${CONFIG_DIR}/fxflow-tunnel.log"

  mkdir -p "${PLIST_DIR}"

  cat > "${PLIST_FILE}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.fxflow.tunnel</string>
  <key>ProgramArguments</key>
  <array>
    <string>${CLOUDFLARED_PATH}</string>
    <string>tunnel</string>
    <string>run</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
</dict>
</plist>
EOF

  echo "✓ LaunchAgent created: ${PLIST_FILE}"
  echo ""

  launchctl load "${PLIST_FILE}" 2>/dev/null || true
  echo "✓ Tunnel service started"
  echo "  Logs: ${LOG_FILE}"
  echo ""
  echo "  To stop:   launchctl unload ${PLIST_FILE}"
  echo "  To start:  launchctl load ${PLIST_FILE}"
else
  echo ""
  echo "  To start the tunnel manually:"
  echo "  cloudflared tunnel run"
  echo ""
  echo "  To set up auto-start later, run this script again."
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Next steps:"
echo "  1. Start FXFlow: pnpm dev (or pnpm build && pnpm start)"
echo "  2. Start tunnel: cloudflared tunnel run"
echo "  3. Open on your phone: https://${TUNNEL_ID}.cfargotunnel.com"
echo ""
echo "  Optional — Add Cloudflare Access for authentication:"
echo "  → https://one.dash.cloudflare.com → Access → Applications"
echo "  → Create app → Self-hosted → Add your tunnel URL"
echo "  → Policy: email OTP to your email address"
echo ""
